"""Shared helpers for the build, upload, scan and test tools.

Standard library only.
"""

from __future__ import annotations

import base64
import json
import re
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "qa.manifest.json"
LIB_FILES = ROOT / "src" / "lib" / "files.json"
MAIN_SOURCE = ROOT / "src" / "main.lua"

INFO_FILE = "QaInfo"
FILE_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9]{0,31}$")
LOG_TAG = re.compile(r"^[A-Za-z][A-Za-z0-9_]{1,23}$")
ENTRY_POINT = re.compile(r"function\s+QuickApp:(\w+)\s*\([^)]*\)\s*\n\s*(\S[^\n]*)")
SEMVER = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z.-]+)?$")
VARIABLE_TYPES = {"string", "password"}
UI_TYPES = {"label", "button"}
BUTTON_EVENTS = ("onReleased", "onLongPressDown", "onLongPressReleased")


class QaError(Exception):
    """A problem the user has to fix; printed without a traceback."""


# --- manifest and sources ---------------------------------------------------

def load_manifest() -> dict:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def repo_name(manifest: dict) -> str:
    return manifest["repository"].rstrip("/").rsplit("/", 1)[-1]


def lua_string(value: str) -> str:
    """A Lua string literal; JSON escaping is valid Lua for these characters."""
    return json.dumps(value, ensure_ascii=False)


def info_source(manifest: dict) -> str:
    return (
        "-- Generated by tools/qa.py from qa.manifest.json. Do not edit.\n"
        "-- Loaded first, so even the earliest log line carries the QuickApp's tag.\n"
        f"__TAG = {lua_string(manifest['logTag'])}\n"
        f"QA_INFO = {{ name = {lua_string(manifest['name'])}, "
        f"version = {lua_string(manifest['version'])}, "
        f"logTag = {lua_string(manifest['logTag'])}, "
        f"repository = {lua_string(manifest['repository'])} }}\n"
    )


def file_entries(manifest: dict) -> list[dict]:
    """All QuickApp files in load order: generated info, library, project."""
    lib = json.loads(LIB_FILES.read_text(encoding="utf-8"))["files"]
    entries = [{"name": INFO_FILE, "path": None, "isMain": False}]
    entries += [{"name": e["name"], "path": e["path"], "isMain": False} for e in lib]
    entries += [{"name": e["name"], "path": e["path"], "isMain": bool(e.get("isMain"))}
                for e in manifest["files"]]
    return entries


def collect_files(manifest: dict) -> list[dict]:
    """File entries with their content: [{name, isMain, content}]."""
    result = []
    for entry in file_entries(manifest):
        if entry["path"] is None:
            content = info_source(manifest)
        else:
            path = ROOT / entry["path"]
            if not path.is_file():
                raise QaError(f"{entry['path']} is listed but missing")
            content = path.read_text(encoding="utf-8")
        result.append({"name": entry["name"], "isMain": entry["isMain"], "content": content})
    return result


def validate(manifest: dict) -> list[str]:
    """Structural checks the offline Lua tests cannot do. Returns problems."""
    problems = []
    for key in ("name", "logTag", "version", "type", "repository", "files"):
        if not manifest.get(key):
            problems.append(f"manifest: '{key}' is missing")
    if problems:
        return problems

    icon = manifest.get("deviceIcon")
    if icon is not None and (not isinstance(icon, int) or isinstance(icon, bool) or icon <= 0):
        problems.append("manifest: deviceIcon must be the ID of a built-in HC3 device icon")

    if not SEMVER.match(manifest["version"]):
        problems.append(f"manifest: version '{manifest['version']}' is not SemVer (MAJOR.MINOR.PATCH)")

    if not LOG_TAG.match(manifest["logTag"]):
        problems.append(f"manifest: logTag '{manifest['logTag']}' must be 2-24 letters, digits or underscores")

    entries = file_entries(manifest)
    names = [e["name"] for e in entries]
    for name in names:
        if not FILE_NAME.match(name):
            problems.append(f"file name '{name}': use letters and digits only, max. 32")
    duplicates = {n for n in names if names.count(n) > 1}
    if duplicates:
        problems.append(f"duplicate file names: {', '.join(sorted(duplicates))}")
    mains = [e for e in entries if e["isMain"]]
    if len(mains) != 1 or entries[-1] is not mains[0]:
        problems.append("exactly one file must have isMain, and it must be the last one")

    for var in manifest.get("quickAppVariables", []):
        if var.get("type") not in VARIABLE_TYPES:
            problems.append(f"variable '{var.get('name')}': type must be one of {sorted(VARIABLE_TYPES)}")
        if not isinstance(var.get("value"), str):
            problems.append(f"variable '{var.get('name')}': value must be a string")

    main_source = MAIN_SOURCE.read_text(encoding="utf-8") if MAIN_SOURCE.is_file() else ""
    # An uncaught error is logged by the HC3 under QUICKAPP<id>, not our tag,
    # and stops the QuickApp - so every entry point must start with Safe.call.
    for method, first_line in ENTRY_POINT.findall(main_source):
        if not first_line.startswith("Safe.call("):
            problems.append(f"src/main.lua: QuickApp:{method} must start with Safe.call(...)")
    seen_ids = set()
    for row in manifest.get("ui", []):
        for element in row:
            element_id = element.get("id", "")
            if element.get("type") not in UI_TYPES:
                problems.append(f"ui '{element_id}': type must be one of {sorted(UI_TYPES)}")
            if not re.match(r"^[A-Za-z][A-Za-z0-9_]*$", element_id):
                problems.append(f"ui element id '{element_id}' is invalid")
            if element_id in seen_ids:
                problems.append(f"ui element id '{element_id}' is used twice")
            seen_ids.add(element_id)
            for event in button_events(element):
                if event not in BUTTON_EVENTS:
                    problems.append(f"ui '{element_id}': unknown event '{event}'")
                    continue
                callback = callback_name(element_id, event)
                if not re.search(rf"function\s+QuickApp:{re.escape(callback)}\s*\(", main_source):
                    problems.append(f"ui '{element_id}': QuickApp:{callback} not found in src/main.lua "
                                    "(the HC3 calls exactly this name)")
    return problems


# --- .fqa -------------------------------------------------------------------

def button_events(element: dict) -> list[str]:
    return element.get("events", ["onReleased"]) if element.get("type") == "button" else []


def callback_name(element_id: str, event: str) -> str:
    """The handler name the HC3 assigns on import, e.g. uibtnRefreshOnReleased."""
    return f"ui{element_id}{event[0].upper()}{event[1:]}"


def _weight(count: int) -> str:
    return f"{1 / count:.2f}"


def _ui_component(element: dict, weight: str, for_layout: bool) -> dict:
    component = {"name": element["id"], "text": element.get("text", ""),
                 "type": element["type"], "style": {"weight": weight}}
    if element["type"] == "button":
        component["visible"] = True
        if not for_layout:
            component["eventBinding"] = {
                event: [{"type": "deviceAction",
                         "params": {"actionName": "UIAction", "args": [event, element["id"]]}}]
                for event in BUTTON_EVENTS
            }
    return component


def build_fqa(manifest: dict, files: list[dict]) -> dict:
    """Assemble an .fqa (apiVersion 1.3) from the manifest - never from a controller."""
    rows = manifest.get("ui", [])
    ui_view = [{"type": "horizontal", "style": {"weight": "1.0"},
                "components": [_ui_component(e, _weight(len(row)), False) for e in row]}
               for row in rows]
    layout_items = [{"type": "horizontal", "style": {"weight": "1.0"},
                     "components": [_ui_component(e, _weight(len(row)), True) for e in row]}
                    for row in rows]
    callbacks = [{"name": e["id"], "eventType": event, "callback": callback_name(e["id"], event)}
                 for row in rows for e in row for event in button_events(e)]
    properties = {
        "viewLayout": {
            "$jason": {
                "head": {"title": "quickApp_device"},
                "body": {"header": {"style": {"height": "0"}, "title": "quickApp_device"},
                         "sections": {"items": layout_items}},
            },
        },
        "uiView": ui_view,
        "useUiView": True,
        "uiCallbacks": callbacks,
        "quickAppVariables": [{"name": v["name"], "type": v["type"], "value": v["value"]}
                              for v in manifest.get("quickAppVariables", [])],
        "typeTemplateInitialized": True,
        "userDescription": manifest.get("userDescription", ""),
    }
    if manifest.get("deviceIcon"):
        # A built-in icon ID; the HC3 applies it on import (verified on 5.220.11).
        properties["deviceIcon"] = manifest["deviceIcon"]
    return {
        "name": manifest["name"],
        "type": manifest["type"],
        "apiVersion": "1.3",
        "initialInterfaces": manifest.get("initialInterfaces", []),
        "initialProperties": properties,
        "files": [{"name": f["name"], "isMain": f["isMain"], "isOpen": False,
                   "content": f["content"]} for f in files],
    }


# --- environment and HC3 access ---------------------------------------------

def load_env() -> dict[str, str]:
    """Merge ../.env (shared workspace) and ./.env (repository); the repository wins."""
    env: dict[str, str] = {}
    for path in (ROOT.parent / ".env", ROOT / ".env"):
        if not path.is_file():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            value = value.split(" #", 1)[0].strip().strip('"').strip("'")
            if value:
                env[key.strip()] = value
    return env


class Hc3:
    """Minimal HC3 REST client with Basic auth and retries."""

    def __init__(self, env: dict[str, str], attempts: int = 4):
        missing = [k for k in ("HC3_URL", "HC3_USER", "HC3_PASSWORD") if not env.get(k)]
        if missing:
            raise QaError(f"missing in .env: {', '.join(missing)}")
        self.base = env["HC3_URL"].rstrip("/")
        token = base64.b64encode(f"{env['HC3_USER']}:{env['HC3_PASSWORD']}".encode()).decode()
        self.auth = f"Basic {token}"
        self.attempts = attempts

    def request(self, method: str, path: str, body=None):
        data = None if body is None else json.dumps(body).encode("utf-8")
        for attempt in range(1, self.attempts + 1):
            req = urllib.request.Request(self.base + path, data=data, method=method)
            req.add_header("Authorization", self.auth)
            req.add_header("Accept", "application/json")
            if data is not None:
                req.add_header("Content-Type", "application/json")
            try:
                with urllib.request.urlopen(req, timeout=30) as resp:
                    raw = resp.read()
                    # The HC3 may return invalid UTF-8 (device "log" property).
                    text = raw.decode("utf-8", errors="replace")
                    return json.loads(text) if text.strip() else None
            except urllib.error.HTTPError as err:
                # The controller answers 5xx when it is busy; client errors are final.
                if err.code < 500 or attempt == self.attempts:
                    raise QaError(f"{method} {path} failed: HTTP {err.code}") from None
            except (urllib.error.URLError, TimeoutError, ConnectionError) as err:
                if attempt == self.attempts:
                    raise QaError(f"{method} {path} failed: {err}") from None
            time.sleep(2 ** attempt)
        return None
