-- Strings: every text this QuickApp shows in the HC3 user interface.
-- English is the default. FR and IT are not reviewed by a native speaker;
-- corrections are welcome.

Strings = {
  ["ui.refresh"] = {
    en = "Refresh",
    de = "Aktualisieren",
    fr = "Actualiser",
    it = "Aggiorna",
  },
  ["status.loggingIn"] = {
    en = "Logging in to the inverter (takes about 20 s)…",
    de = "Anmeldung am Wechselrichter (dauert etwa 20 s)…",
    fr = "Connexion à l’onduleur (environ 20 s)…",
    it = "Accesso all’inverter (circa 20 s)…",
  },
  ["status.online"] = {
    en = "PV {pv} W · battery {soc} % · {time}",
    de = "PV {pv} W · Batterie {soc} % · {time}",
    fr = "PV {pv} W · batterie {soc} % · {time}",
    it = "FV {pv} W · batteria {soc} % · {time}",
  },
  ["status.unreachable"] = {
    en = "Inverter not reachable – next attempt in {seconds} s",
    de = "Wechselrichter nicht erreichbar – neuer Versuch in {seconds} s",
    fr = "Onduleur injoignable – nouvel essai dans {seconds} s",
    it = "Inverter non raggiungibile – nuovo tentativo tra {seconds} s",
  },
  ["status.authFailed"] = {
    en = "Login rejected – please check the password",
    de = "Anmeldung abgelehnt – bitte Passwort prüfen",
    fr = "Connexion refusée – veuillez vérifier le mot de passe",
    it = "Accesso rifiutato – verificare la password",
  },
  ["status.unsupportedPlatform"] = {
    en = "Controller not supported – 64-bit Lua required",
    de = "Controller nicht unterstützt – 64-Bit-Lua erforderlich",
    fr = "Contrôleur non pris en charge – Lua 64 bits requis",
    it = "Controller non supportato – richiesto Lua a 64 bit",
  },
  ["status.protocolError"] = {
    en = "Unexpected answer from the inverter – see the log",
    de = "Unerwartete Antwort des Wechselrichters – Details im Log",
    fr = "Réponse inattendue de l’onduleur – voir le journal",
    it = "Risposta inattesa dall’inverter – vedere il registro",
  },
  ["value.on"] = {
    en = "on",
    de = "ein",
    fr = "activé",
    it = "attivo",
  },
  ["value.off"] = {
    en = "off",
    de = "aus",
    fr = "désactivé",
    it = "disattivo",
  },

  -- Value names in the value list (value.<name>, see App.Catalog).
  ["value.pvPower"] = {
    en = "PV power",
    de = "PV-Leistung",
    fr = "Puissance PV",
    it = "Potenza FV",
  },
  ["value.pv1Power"] = {
    en = "PV string 1",
    de = "PV-String 1",
    fr = "Chaîne PV 1",
    it = "Stringa FV 1",
  },
  ["value.pv2Power"] = {
    en = "PV string 2",
    de = "PV-String 2",
    fr = "Chaîne PV 2",
    it = "Stringa FV 2",
  },
  ["value.pv3Power"] = {
    en = "PV string 3",
    de = "PV-String 3",
    fr = "Chaîne PV 3",
    it = "Stringa FV 3",
  },
  ["value.acPower"] = {
    en = "AC output",
    de = "AC-Leistung",
    fr = "Puissance AC",
    it = "Potenza CA",
  },
  ["value.homePower"] = {
    en = "Home consumption",
    de = "Hausverbrauch",
    fr = "Consommation",
    it = "Consumo casa",
  },
  ["value.homeFromPv"] = {
    en = "PV → home",
    de = "PV → Haus",
    fr = "PV → maison",
    it = "FV → casa",
  },
  ["value.homeFromBattery"] = {
    en = "Battery → home",
    de = "Batterie → Haus",
    fr = "Batterie → maison",
    it = "Batteria → casa",
  },
  ["value.homeFromGrid"] = {
    en = "Grid → home",
    de = "Netz → Haus",
    fr = "Réseau → maison",
    it = "Rete → casa",
  },
  ["value.gridPower"] = {
    en = "Grid power",
    de = "Netzleistung",
    fr = "Puissance réseau",
    it = "Potenza di rete",
  },
  ["value.batteryPower"] = {
    en = "Battery power",
    de = "Batterieleistung",
    fr = "Puissance batterie",
    it = "Potenza batteria",
  },
  ["value.batterySoc"] = {
    en = "Battery charge",
    de = "Batterie-Ladestand",
    fr = "Charge batterie",
    it = "Carica batteria",
  },
  ["value.batteryCycles"] = {
    en = "Battery cycles",
    de = "Batteriezyklen",
    fr = "Cycles batterie",
    it = "Cicli batteria",
  },
  ["value.inverterState"] = {
    en = "Inverter state",
    de = "Wechselrichter-Status",
    fr = "État de l’onduleur",
    it = "Stato inverter",
  },
  ["value.energyManagerState"] = {
    en = "Energy manager",
    de = "Energiemanager",
    fr = "Gestionnaire d’énergie",
    it = "Gestore energia",
  },
  ["value.yieldDay"] = {
    en = "PV yield today",
    de = "PV-Ertrag heute",
    fr = "Production PV aujourd’hui",
    it = "Produzione FV oggi",
  },
  ["value.yieldTotal"] = {
    en = "PV yield total",
    de = "PV-Ertrag gesamt",
    fr = "Production PV total",
    it = "Produzione FV totale",
  },
  ["value.homeDay"] = {
    en = "Home consumption today",
    de = "Hausverbrauch heute",
    fr = "Consommation aujourd’hui",
    it = "Consumo casa oggi",
  },
  ["value.homeTotal"] = {
    en = "Home consumption total",
    de = "Hausverbrauch gesamt",
    fr = "Consommation total",
    it = "Consumo casa totale",
  },
  ["value.homeFromGridDay"] = {
    en = "Grid → home today",
    de = "Netz → Haus heute",
    fr = "Réseau → maison aujourd’hui",
    it = "Rete → casa oggi",
  },
  ["value.homeFromGridTotal"] = {
    en = "Grid → home total",
    de = "Netz → Haus gesamt",
    fr = "Réseau → maison total",
    it = "Rete → casa totale",
  },
  ["value.homeFromPvDay"] = {
    en = "PV → home today",
    de = "PV → Haus heute",
    fr = "PV → maison aujourd’hui",
    it = "FV → casa oggi",
  },
  ["value.homeFromPvTotal"] = {
    en = "PV → home total",
    de = "PV → Haus gesamt",
    fr = "PV → maison total",
    it = "FV → casa totale",
  },
  ["value.homeFromBatteryDay"] = {
    en = "Battery → home today",
    de = "Batterie → Haus heute",
    fr = "Batterie → maison aujourd’hui",
    it = "Batteria → casa oggi",
  },
  ["value.homeFromBatteryTotal"] = {
    en = "Battery → home total",
    de = "Batterie → Haus gesamt",
    fr = "Batterie → maison total",
    it = "Batteria → casa totale",
  },
  ["value.batteryChargePvDay"] = {
    en = "PV → battery today",
    de = "PV → Batterie heute",
    fr = "PV → batterie aujourd’hui",
    it = "FV → batteria oggi",
  },
  ["value.batteryChargePvTotal"] = {
    en = "PV → battery total",
    de = "PV → Batterie gesamt",
    fr = "PV → batterie total",
    it = "FV → batteria totale",
  },
  ["value.batteryChargeGridDay"] = {
    en = "Grid → battery today",
    de = "Netz → Batterie heute",
    fr = "Réseau → batterie aujourd’hui",
    it = "Rete → batteria oggi",
  },
  ["value.batteryChargeGridTotal"] = {
    en = "Grid → battery total",
    de = "Netz → Batterie gesamt",
    fr = "Réseau → batterie total",
    it = "Rete → batteria totale",
  },
  ["value.batteryDischargeDay"] = {
    en = "Battery discharge today",
    de = "Batterie-Entladung heute",
    fr = "Décharge batterie aujourd’hui",
    it = "Scarica batteria oggi",
  },
  ["value.batteryDischargeTotal"] = {
    en = "Battery discharge total",
    de = "Batterie-Entladung gesamt",
    fr = "Décharge batterie total",
    it = "Scarica batteria totale",
  },
  ["value.autarkyDay"] = {
    en = "Autarky today",
    de = "Autarkie heute",
    fr = "Autarcie aujourd’hui",
    it = "Autarchia oggi",
  },
  ["value.selfConsumptionDay"] = {
    en = "Self-consumption today",
    de = "Eigenverbrauch heute",
    fr = "Autoconsommation aujourd’hui",
    it = "Autoconsumo oggi",
  },
  ["value.batteryMinSoc"] = {
    en = "Min. battery charge",
    de = "Min. Batterie-Ladestand",
    fr = "Charge min. batterie",
    it = "Carica min. batteria",
  },
  ["value.batteryMinHomeConsumption"] = {
    en = "Battery use from",
    de = "Batterienutzung ab",
    fr = "Batterie utilisée dès",
    it = "Batteria usata da",
  },
  ["value.batterySmartControl"] = {
    en = "Smart battery control",
    de = "Intelligente Batteriesteuerung",
    fr = "Gestion intelligente de la batterie",
    it = "Gestione intelligente batteria",
  },
  ["value.batteryDynamicSoc"] = {
    en = "Dynamic min. charge",
    de = "Dynamischer Mindest-Ladestand",
    fr = "Charge min. dynamique",
    it = "Carica min. dinamica",
  },
  ["value.batteryStrategy"] = {
    en = "Battery strategy",
    de = "Batteriestrategie",
    fr = "Stratégie batterie",
    it = "Strategia batteria",
  },
  ["value.batteryTimeControl"] = {
    en = "Time control",
    de = "Zeitsteuerung",
    fr = "Commande horaire",
    it = "Controllo orario",
  },
  ["value.batteryTimeControlMon"] = {
    en = "Time control Monday",
    de = "Zeitsteuerung Montag",
    fr = "Commande horaire lundi",
    it = "Controllo orario lunedì",
  },
  ["value.batteryTimeControlTue"] = {
    en = "Time control Tuesday",
    de = "Zeitsteuerung Dienstag",
    fr = "Commande horaire mardi",
    it = "Controllo orario martedì",
  },
  ["value.batteryTimeControlWed"] = {
    en = "Time control Wednesday",
    de = "Zeitsteuerung Mittwoch",
    fr = "Commande horaire mercredi",
    it = "Controllo orario mercoledì",
  },
  ["value.batteryTimeControlThu"] = {
    en = "Time control Thursday",
    de = "Zeitsteuerung Donnerstag",
    fr = "Commande horaire jeudi",
    it = "Controllo orario giovedì",
  },
  ["value.batteryTimeControlFri"] = {
    en = "Time control Friday",
    de = "Zeitsteuerung Freitag",
    fr = "Commande horaire vendredi",
    it = "Controllo orario venerdì",
  },
  ["value.batteryTimeControlSat"] = {
    en = "Time control Saturday",
    de = "Zeitsteuerung Samstag",
    fr = "Commande horaire samedi",
    it = "Controllo orario sabato",
  },
  ["value.batteryTimeControlSun"] = {
    en = "Time control Sunday",
    de = "Zeitsteuerung Sonntag",
    fr = "Commande horaire dimanche",
    it = "Controllo orario domenica",
  },
  ["value.activePowerLimitation"] = {
    en = "Power limitation",
    de = "Leistungsbegrenzung",
    fr = "Limitation de puissance",
    it = "Limitazione di potenza",
  },
  ["value.shadowManagement"] = {
    en = "Shade management",
    de = "Schattenmanagement",
    fr = "Gestion de l’ombrage",
    it = "Gestione ombreggiamento",
  },
  ["value.model"] = {
    en = "Model",
    de = "Modell",
    fr = "Modèle",
    it = "Modello",
  },
  ["value.firmwareVersion"] = {
    en = "Firmware",
    de = "Firmware",
    fr = "Micrologiciel",
    it = "Firmware",
  },
  ["value.batteryType"] = {
    en = "Battery type",
    de = "Batterietyp",
    fr = "Type de batterie",
    it = "Tipo di batteria",
  },
  ["value.batteryExternalControl"] = {
    en = "Battery control",
    de = "Batteriesteuerung",
    fr = "Pilotage de la batterie",
    it = "Controllo batteria",
  },
}
